[phases.setup]
nixpkgs = ["...", "nodejs"]

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

[phases.install]
dependsOn = ["setup"]
cmds = ["npm install"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]

[start]
cmd = "npm start"