# Nixpacks configuration for MB-Sparrow backend
# This ensures proper Python environment and system dependencies

[phases.setup]
# Use Python 3.10 for better compatibility
nixPkgs = ["python310", "python310Packages.pip", "gcc", "stdenv.cc.cc.lib", "zlib", "libjpeg", "libpng", "freetype", "pkg-config", "cairo", "pango", "gdk-pixbuf", "glib"]

[phases.install]
# Install Python dependencies with proper pip settings
cmds = [
    "python -m pip install --upgrade pip setuptools wheel",
    "python -m pip install pypika==0.48.9",
    "python -m pip install tiktoken --no-binary tiktoken",
    "python -m pip install -r requirements.txt"
]

[phases.build]
# No build phase needed for Python apps
cmds = []

[start]
# Use system Python
cmd = "python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
# Python environment variables
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PIP_NO_CACHE_DIR = "1"