# Nixpacks configuration for MB-Sparrow backend
# This ensures proper Python environment and system dependencies

[phases.setup]
# Use Python 3.11 for better compatibility with tiktoken and other packages
nixPkgs = ["python311", "gcc", "stdenv.cc.cc.lib", "zlib", "libjpeg", "libpng", "freetype"]

[phases.install]
# Install Python dependencies with proper pip settings
cmds = [
    "python -m venv venv",
    ". venv/bin/activate",
    "pip install --upgrade pip setuptools wheel",
    "pip install pypika==0.48.9",
    "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
# No build phase needed for Python apps
cmds = []

[start]
# Use the virtual environment's Python
cmd = "venv/bin/uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
# Python environment variables
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"