# Railway deployment configuration for MB-Sparrow with Supabase (no local PostgreSQL)
# This configuration deploys backend, frontend, Celery workers, and Redis only
# All database operations use Supabase PostgreSQL

[build]
builder = "nixpacks"
buildCommand = "npm run build:all"
startCommand = "npm run start:prod"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/api/health"
healthcheckTimeout = 300

[environments.production]
# Backend service
[environments.production.services.backend]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 300

# Frontend service
[environments.production.services.frontend]
startCommand = "npm run start:frontend"
healthcheckPath = "/"
healthcheckTimeout = 300

# Celery worker
[environments.production.services.celery]
startCommand = "celery -A app.celery_app worker --loglevel=info --concurrency=2"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

# Celery beat scheduler
[environments.production.services.celery-beat]
startCommand = "celery -A app.celery_app beat --loglevel=info"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Redis service (managed by Railway)
[environments.production.services.redis]
image = "redis:7-alpine"
ports = [6379]

[variables]
# Supabase Configuration (Primary Database)
SUPABASE_URL=https://your-project.supabase.co
SUPABASE_ANON_KEY=your_supabase_anon_key
SUPABASE_SERVICE_KEY=your_supabase_service_key

# Redis Configuration (Railway managed)
REDIS_URL=redis://localhost:6379
REDIS_HOST=localhost
REDIS_PORT=6379

# API Keys (Set via Railway Environment Variables)
GEMINI_API_KEY=your_gemini_api_key
TAVILY_API_KEY=your_tavily_api_key
FIRECRAWL_API_KEY=your_firecrawl_api_key

# Security Configuration
API_KEY_ENCRYPTION_SECRET=your_32_character_encryption_key_here
JWT_SECRET_KEY=your_jwt_secret_key_here
JWT_ALGORITHM=HS256
JWT_EXPIRATION_HOURS=24

# Application Configuration
ENVIRONMENT=production
DEBUG=false
LOG_LEVEL=INFO

# FeedMe Configuration
FEEDME_MAX_FILE_SIZE=10485760
FEEDME_ALLOWED_EXTENSIONS=txt,pdf,doc,docx
FEEDME_PROCESSING_TIMEOUT=300

# Railway-specific settings
PORT=8000
HOST=0.0.0.0

# Supabase Database (no local PostgreSQL needed)
DATABASE_URL=${SUPABASE_URL}

[resources.backend]
cpu = "1"
memory = "2Gi"

[resources.frontend]
cpu = "0.5"
memory = "1Gi"

[resources.celery]
cpu = "1"
memory = "2Gi"

[resources.celery-beat]
cpu = "0.25"
memory = "512Mi"

[resources.redis]
cpu = "0.5"
memory = "512Mi"
