"use client";

import React, { memo, useEffect, useRef, useState, useCallback } from "react";
import {
  X,
  Copy,
  Check,
  Download,
  Maximize2,
  Minimize2,
  Code,
  Eye,
  GripVertical,
  ChevronLeft,
  ChevronRight,
  Trash2,
  Edit3,
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import mermaid from "mermaid";
import { cn } from "@/shared/lib/utils";
import { LinkPreview } from "@/components/ui/link-preview";
import {
  useCurrentArtifact,
  useArtifactsVisible,
  useArtifactStore,
  useArtifactSelector,
} from "./ArtifactContext";
import { MermaidEditor } from "./MermaidEditor";
import { ArticleEditor } from "./ArticleEditor";
import type { Artifact } from "./types";
import { useAgent } from "@/features/librechat/AgentContext";
import { sessionsAPI } from "@/services/api/endpoints/sessions";

interface ResizeHandleProps {
  direction: string;
  className: string;
  isActive: boolean;
  onResizeStart: (event: React.MouseEvent, direction: string) => void;
}

function ResizeHandle({
  direction,
  className,
  isActive,
  onResizeStart,
}: ResizeHandleProps) {
  const cursor =
    direction.includes("n") && direction.includes("e")
      ? "nesw-resize"
      : direction.includes("n") && direction.includes("w")
        ? "nwse-resize"
        : direction.includes("s") && direction.includes("e")
          ? "nwse-resize"
          : direction.includes("s") && direction.includes("w")
            ? "nesw-resize"
            : direction.includes("n") || direction.includes("s")
              ? "ns-resize"
              : "ew-resize";

  return (
    <div
      className={cn(
        "absolute z-10 opacity-0 hover:opacity-100 transition-opacity",
        className,
        isActive && "opacity-100",
      )}
      onMouseDown={(e) => onResizeStart(e, direction)}
      style={{ cursor }}
    />
  );
}

// Initialize mermaid with dark theme
mermaid.initialize({
  startOnLoad: false,
  theme: "dark",
  themeVariables: {
    primaryColor: "#c4704f",
    primaryTextColor: "#faf6f0",
    primaryBorderColor: "#c4704f",
    lineColor: "#8b7355",
    secondaryColor: "#2d2a26",
    tertiaryColor: "#1a1816",
    background: "#1a1816",
    mainBkg: "#2d2a26",
    nodeBorder: "#c4704f",
    clusterBkg: "#2d2a26",
    titleColor: "#faf6f0",
    edgeLabelBackground: "#2d2a26",
  },
  flowchart: {
    curve: "basis",
    padding: 20,
  },
  securityLevel: "strict",
});

/**
 * Sanitize mermaid content to fix common parsing issues.
 * Models sometimes generate invalid syntax like <br/> tags.
 */
function sanitizeMermaidContent(content: string): string {
  let sanitized = content;

  // Replace <br/> and <br> tags with newlines in node labels
  // These are commonly generated by LLMs but not valid mermaid syntax
  sanitized = sanitized.replace(/<br\s*\/?>/gi, "\\n");

  // Remove HTML entities that might cause issues
  sanitized = sanitized.replace(/&nbsp;/g, " ");
  sanitized = sanitized.replace(/&amp;/g, "&");
  sanitized = sanitized.replace(/&lt;/g, "<");
  sanitized = sanitized.replace(/&gt;/g, ">");

  // Fix parentheses inside node labels that cause parsing issues
  // Replace (text) with [text] inside square brackets
  // Pattern: [content(inner)more] -> [content - inner - more]
  sanitized = sanitized.replace(
    /\[([^\]]*)\(([^)]*)\)([^\]]*)\]/g,
    (match, before, inner, after) => {
      return `[${before}${inner}${after}]`;
    },
  );

  return sanitized;
}

function toExternalHttpUrl(value?: string | null): string | null {
  if (!value) return null;
  const trimmed = value.trim();
  if (!trimmed) return null;
  try {
    const url = new URL(trimmed);
    if (url.protocol === "http:" || url.protocol === "https:") {
      return url.toString();
    }
  } catch {
    // Ignore invalid URL values from artifact payloads
  }
  return null;
}

interface MermaidRendererProps {
  content: string;
  id: string;
}

/**
 * MermaidRenderer - Renders mermaid diagram content
 */
const MermaidRenderer = memo(function MermaidRenderer({
  content,
  id,
}: MermaidRendererProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [svg, setSvg] = useState<string>("");
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;

    const renderDiagram = async () => {
      // Handle missing content
      if (!content) {
        setError("No diagram content provided");
        setIsLoading(false);
        return;
      }

      setIsLoading(true);
      setError(null);

      try {
        // Generate unique ID for this render
        const rendererId = `mermaid-${id}-${Date.now()}`;

        // Sanitize content to fix common LLM-generated syntax issues
        const sanitizedContent = sanitizeMermaidContent(content);

        // Render the diagram
        const { svg: renderedSvg } = await mermaid.render(
          rendererId,
          sanitizedContent,
        );

        if (!cancelled) {
          setSvg(renderedSvg);
          setIsLoading(false);
        }
      } catch (err) {
        if (!cancelled) {
          console.error("Mermaid render error:", err);
          setError(
            err instanceof Error ? err.message : "Failed to render diagram",
          );
          setIsLoading(false);
        }
      }
    };

    renderDiagram();

    return () => {
      cancelled = true;
    };
  }, [content, id]);

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64 text-muted-foreground">
        <div className="flex items-center gap-2">
          <div className="animate-spin h-5 w-5 border-2 border-primary border-t-transparent rounded-full" />
          <span>Rendering diagram...</span>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-4 bg-red-500/10 border border-red-500/20 rounded-lg">
        <p className="text-red-400 font-medium">Diagram Error</p>
        <p className="text-red-300 text-sm mt-1">{error}</p>
        <pre className="mt-2 text-xs text-muted-foreground bg-secondary/50 p-2 rounded overflow-auto">
          {content}
        </pre>
      </div>
    );
  }

  return (
    <div
      ref={containerRef}
      className="mermaid-container flex items-center justify-center p-4 overflow-auto"
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
});

/**
 * CodeRenderer - Renders code artifacts with syntax highlighting
 */
const CodeRenderer = memo(function CodeRenderer({
  content,
  language,
}: {
  content: string;
  language?: string;
}) {
  return (
    <div className="relative overflow-auto rounded-lg">
      <pre className="p-4 bg-[hsl(var(--code-block-bg))] text-sm font-mono">
        <code className={language ? `language-${language}` : ""}>
          {content}
        </code>
      </pre>
    </div>
  );
});

const ARTIFACT_MARKER_PATTERN = /^(?:\/\/|\/\*|#)\s*artifact(?:\s*\*\/)?/i;
const ARTIFACT_DIRECTIVE_PATTERN = /^[ \t]*::artifact\{[^}]+\}[^\n]*$/gm;
const CODE_FENCE_PATTERN = /^```([^\n]*)\n([\s\S]*?)^```/gm;

const normalizeFenceContent = (value: string): string =>
  value.replace(/\n+$/, "");

const ensureArtifactMarker = (
  content: string,
  markerLine: string | null,
): string => {
  if (!markerLine) return content;
  const firstLine = content.split("\n")[0] ?? "";
  if (ARTIFACT_MARKER_PATTERN.test(firstLine.trim())) {
    return content;
  }
  const trimmed = content.replace(/^\n+/, "");
  return `${markerLine}\n${trimmed}`;
};

const updateArtifactInMarkdown = (
  markdown: string,
  targetIndex: number,
  nextContent: string,
): string | null => {
  if (!Number.isFinite(targetIndex)) return null;

  const matches: Array<{
    kind: "directive" | "code";
    index: number;
    raw: string;
    lang?: string;
    content?: string;
  }> = [];

  for (const match of markdown.matchAll(ARTIFACT_DIRECTIVE_PATTERN)) {
    matches.push({
      kind: "directive",
      index: match.index ?? 0,
      raw: match[0],
    });
  }

  for (const match of markdown.matchAll(CODE_FENCE_PATTERN)) {
    matches.push({
      kind: "code",
      index: match.index ?? 0,
      raw: match[0],
      lang: match[1] ?? "",
      content: match[2] ?? "",
    });
  }

  matches.sort((a, b) => a.index - b.index);

  let cursor = 0;
  let artifactIndex = 0;
  let didUpdate = false;
  const chunks: string[] = [];

  for (const match of matches) {
    chunks.push(markdown.slice(cursor, match.index));

    if (match.kind === "directive") {
      chunks.push(match.raw);
      artifactIndex += 1;
    } else {
      const langInfo = match.lang ?? "";
      const lang = langInfo.trim().split(/\s+/)[0]?.toLowerCase() ?? "";
      const content = match.content ?? "";
      const firstLine = content.split("\n")[0] ?? "";
      const hasMarker = ARTIFACT_MARKER_PATTERN.test(firstLine.trim());
      const isArtifact = lang === "mermaid" || hasMarker;

      if (isArtifact) {
        if (artifactIndex === targetIndex && !didUpdate) {
          const markerLine = hasMarker ? firstLine : null;
          const updated = ensureArtifactMarker(nextContent, markerLine);
          const normalized = normalizeFenceContent(updated);
          const fence = langInfo ? `\`\`\`${langInfo}` : "```";
          chunks.push(`${fence}\n${normalized}\n\`\`\``);
          didUpdate = true;
        } else {
          chunks.push(match.raw);
        }
        artifactIndex += 1;
      } else {
        chunks.push(match.raw);
      }
    }

    cursor = match.index + match.raw.length;
  }

  chunks.push(markdown.slice(cursor));

  return didUpdate ? chunks.join("") : null;
};

const getDefaultViewMode = (
  type?: Artifact["type"],
): "preview" | "code" | "editor" => {
  if (type === "react" || type === "code") return "code";
  return "preview";
};

interface CodeEditorProps {
  value: string;
  language?: string;
  placeholder?: string;
  onChange: (value: string) => void;
  onBlur?: () => void;
}

const CodeEditor = memo(function CodeEditor({
  value,
  language,
  placeholder,
  onChange,
  onBlur,
}: CodeEditorProps) {
  return (
    <div className="flex flex-col h-full">
      <div className="px-3 py-1.5 text-xs font-medium text-muted-foreground bg-secondary/50 border-b border-border">
        {language ? `${language} source` : "Source"}
      </div>
      <textarea
        value={value}
        onChange={(event) => onChange(event.target.value)}
        onBlur={onBlur}
        className={cn(
          "flex-1 p-4 font-mono text-sm resize-none",
          "bg-[hsl(var(--code-block-bg))] text-foreground",
          "focus:outline-none focus:ring-2 focus:ring-primary/20",
          "placeholder:text-muted-foreground/50",
        )}
        placeholder={placeholder}
        spellCheck={false}
      />
    </div>
  );
});

// Default panel dimensions and position
const DEFAULT_WIDTH = 800;
const DEFAULT_HEIGHT = 600;
const MIN_WIDTH = 400;
const MIN_HEIGHT = 300;

// Mobile breakpoint
const MOBILE_BREAKPOINT = 768;

/**
 * Hook to detect mobile viewport
 */
function useIsMobile(): boolean {
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    const checkMobile = () => {
      setIsMobile(window.innerWidth < MOBILE_BREAKPOINT);
    };

    // Check on mount
    checkMobile();

    // Listen for resize
    window.addEventListener("resize", checkMobile);
    return () => window.removeEventListener("resize", checkMobile);
  }, []);

  return isMobile;
}

/**
 * ArtifactPanel - Draggable, resizable overlay panel for viewing artifacts
 *
 * Features:
 * - Draggable by header
 * - Resizable from corners and edges
 * - Close with ESC or click outside
 * - Fullscreen toggle
 * - Preview/Code view toggle for mermaid
 */
export const ArtifactPanel = memo(function ArtifactPanel() {
  const artifact = useCurrentArtifact();
  const isVisible = useArtifactsVisible();
  const {
    addArtifact,
    setCurrentArtifact,
    setArtifactsVisible,
    removeArtifact,
  } = useArtifactStore();
  const orderedIds = useArtifactSelector((s) => s.orderedIds);
  const {
    sessionId,
    messages,
    updateMessageContent,
    resolvePersistedMessageId,
  } = useAgent();
  const isMobile = useIsMobile();

  const [copied, setCopied] = useState(false);
  const [viewModeById, setViewModeById] = useState<
    Record<string, "preview" | "code" | "editor">
  >({});
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [draftById, setDraftById] = useState<Record<string, string>>({});
  const [failedImageArtifacts, setFailedImageArtifacts] = useState<
    Record<string, boolean>
  >({});

  const viewMode = artifact
    ? (viewModeById[artifact.id] ?? getDefaultViewMode(artifact.type))
    : "preview";
  const codeDraft = artifact
    ? (draftById[artifact.id] ?? artifact.content)
    : "";
  const isCodeDirty = artifact ? codeDraft !== artifact.content : false;

  const setViewMode = useCallback(
    (mode: "preview" | "code" | "editor") => {
      if (!artifact) return;
      setViewModeById((prev) => ({ ...prev, [artifact.id]: mode }));
      if (mode !== "editor") {
        setDraftById((prev) => {
          if (!(artifact.id in prev)) return prev;
          const { [artifact.id]: _removed, ...rest } = prev;
          return rest;
        });
      }
    },
    [artifact],
  );

  const getCenteredPosition = () => {
    if (typeof window === "undefined") {
      return { x: 0, y: 0 };
    }
    const x = (window.innerWidth - DEFAULT_WIDTH) / 2;
    const y = (window.innerHeight - DEFAULT_HEIGHT) / 2;
    return { x: Math.max(0, x), y: Math.max(0, y) };
  };

  // Panel position and size state (desktop)
  const [position, setPosition] = useState(getCenteredPosition);
  const [size, setSize] = useState({
    width: DEFAULT_WIDTH,
    height: DEFAULT_HEIGHT,
  });
  const [isDragging, setIsDragging] = useState(false);
  const [isResizing, setIsResizing] = useState<string | null>(null);
  const [dragStart, setDragStart] = useState({ x: 0, y: 0 });
  const [initialPos, setInitialPos] = useState({ x: 0, y: 0 });
  const [initialSize, setInitialSize] = useState({ width: 0, height: 0 });

  // Mobile bottom sheet state
  const [mobileHeight, setMobileHeight] = useState(85); // % of viewport height
  const [isMobileDragging, setIsMobileDragging] = useState(false);
  const mobileDragStartY = useRef(0);
  const mobileDragStartHeight = useRef(85);

  const panelRef = useRef<HTMLDivElement>(null);

  // Calculate current artifact index for navigation
  const currentIndex = artifact ? orderedIds.indexOf(artifact.id) : -1;
  const hasMultipleArtifacts = orderedIds.length > 1;
  const isMermaid = artifact?.type === "mermaid";
  const isHtml = artifact?.type === "html";
  const isCodeArtifact =
    artifact?.type === "react" || artifact?.type === "code";

  // Navigate to previous/next artifact
  const handlePrevArtifact = useCallback(() => {
    if (currentIndex > 0) {
      setCurrentArtifact(orderedIds[currentIndex - 1]);
    }
  }, [currentIndex, orderedIds, setCurrentArtifact]);

  const handleNextArtifact = useCallback(() => {
    if (currentIndex < orderedIds.length - 1) {
      setCurrentArtifact(orderedIds[currentIndex + 1]);
    }
  }, [currentIndex, orderedIds, setCurrentArtifact]);

  const handleClose = useCallback(() => {
    if (isMobile) {
      // Reset mobile height on close
      setMobileHeight(85);
    }
    setCurrentArtifact(null);
    setArtifactsVisible(false);
  }, [setCurrentArtifact, setArtifactsVisible, isMobile]);

  // Handle delete artifact
  const handleDelete = useCallback(() => {
    if (!artifact) return;

    const currentId = artifact.id;

    // Navigate to adjacent artifact or close panel
    if (orderedIds.length > 1) {
      // If there are other artifacts, navigate to the previous or next one
      const nextIndex =
        currentIndex < orderedIds.length - 1
          ? currentIndex + 1
          : currentIndex - 1;
      setCurrentArtifact(orderedIds[nextIndex]);
    } else {
      // Last artifact - close the panel
      setCurrentArtifact(null);
      setArtifactsVisible(false);
    }

    // Remove the artifact after navigation
    removeArtifact(currentId);
  }, [
    artifact,
    currentIndex,
    orderedIds,
    setCurrentArtifact,
    setArtifactsVisible,
    removeArtifact,
  ]);

  // Mobile drag handlers for bottom sheet
  const handleMobileDragStart = useCallback(
    (e: React.PointerEvent) => {
      setIsMobileDragging(true);
      mobileDragStartY.current = e.clientY;
      mobileDragStartHeight.current = mobileHeight;
      (e.target as HTMLElement).setPointerCapture(e.pointerId);
    },
    [mobileHeight],
  );

  const handleMobileDragMove = useCallback(
    (e: React.PointerEvent) => {
      if (!isMobileDragging) return;

      const deltaY = mobileDragStartY.current - e.clientY;
      const viewportHeight = window.innerHeight;
      const deltaPercentage = (deltaY / viewportHeight) * 100;
      const newHeight = Math.max(
        20,
        Math.min(100, mobileDragStartHeight.current + deltaPercentage),
      );

      setMobileHeight(newHeight);
    },
    [isMobileDragging],
  );

  const handleMobileDragEnd = useCallback(
    (e: React.PointerEvent) => {
      if (!isMobileDragging) return;

      setIsMobileDragging(false);
      (e.target as HTMLElement).releasePointerCapture(e.pointerId);

      // Snap to positions based on final height
      if (mobileHeight < 30) {
        handleClose();
      } else if (mobileHeight > 90) {
        setMobileHeight(100);
      } else if (mobileHeight < 55) {
        setMobileHeight(50);
      } else {
        setMobileHeight(85);
      }
    },
    [isMobileDragging, mobileHeight, handleClose],
  );

  const handleCopy = useCallback(async () => {
    if (!artifact) return;

    try {
      await navigator.clipboard.writeText(artifact.content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  }, [artifact]);

  const handleDownload = useCallback(async () => {
    if (!artifact) return;

    // Handle image downloads
    if (artifact.type === "image") {
      const mimeType = artifact.mimeType || "image/png";
      const extension = mimeType.split("/")[1] || "png";
      const filename = `${artifact.title.replace(/\s+/g, "_")}.${extension}`;

      if (artifact.imageData) {
        // Convert base64 to blob
        const byteCharacters = atob(artifact.imageData);
        const byteNumbers = new Array(byteCharacters.length);
        for (let i = 0; i < byteCharacters.length; i++) {
          byteNumbers[i] = byteCharacters.charCodeAt(i);
        }
        const byteArray = new Uint8Array(byteNumbers);
        const blob = new Blob([byteArray], { type: mimeType });

        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        return;
      }

      const imageUrl = artifact.content;
      if (imageUrl) {
        try {
          const response = await fetch(imageUrl, { credentials: "omit" });
          if (!response.ok) {
            throw new Error(`HTTP ${response.status}`);
          }
          const blob = await response.blob();
          const url = URL.createObjectURL(blob);
          const a = document.createElement("a");
          a.href = url;
          a.download = filename;
          document.body.appendChild(a);
          a.click();
          document.body.removeChild(a);
          URL.revokeObjectURL(url);
          return;
        } catch (error) {
          console.warn(
            "[ArtifactPanel] Failed to download image via fetch; opening URL",
            error,
          );
          window.open(imageUrl, "_blank", "noopener,noreferrer");
          return;
        }
      }
    }

    const extension =
      artifact.type === "mermaid"
        ? "mmd"
        : artifact.type === "html"
          ? "html"
          : artifact.type === "react"
            ? "tsx"
            : artifact.type === "kb-article"
              ? "md"
              : artifact.language || "txt";

    const blob = new Blob([artifact.content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${artifact.title.replace(/\s+/g, "_")}.${extension}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [artifact]);

  const commitArtifactEdit = useCallback(
    async (target: Artifact, nextContent: string) => {
      if (nextContent === target.content) return;

      addArtifact({
        ...target,
        content: nextContent,
        lastUpdateTime: Date.now(),
      });

      if (typeof target.index !== "number") {
        console.warn(
          "[ArtifactPanel] Missing artifact index; cannot persist changes",
          target.id,
        );
        return;
      }

      const message = messages.find(
        (msg) => String(msg.id) === String(target.messageId),
      );
      const messageContent =
        typeof message?.content === "string" ? message.content : null;
      if (!messageContent) {
        console.warn(
          "[ArtifactPanel] Message content not found for artifact",
          target.id,
        );
        return;
      }

      const updatedContent = updateArtifactInMarkdown(
        messageContent,
        target.index,
        nextContent,
      );
      if (!updatedContent) {
        console.warn(
          "[ArtifactPanel] Unable to locate artifact in message content",
          target.id,
        );
        return;
      }

      updateMessageContent(target.messageId, updatedContent);

      if (sessionId) {
        const persistedId = resolvePersistedMessageId(target.messageId);
        if (!persistedId) {
          console.warn(
            "[ArtifactPanel] Skipping persist for non-persisted message",
            target.messageId,
          );
          return;
        }
        try {
          await sessionsAPI.updateMessage(
            sessionId,
            persistedId,
            updatedContent,
          );
        } catch (error) {
          console.error(
            "[ArtifactPanel] Failed to persist artifact changes",
            error,
          );
        }
      }
    },
    [
      addArtifact,
      messages,
      resolvePersistedMessageId,
      sessionId,
      updateMessageContent,
    ],
  );

  const handleCodeChange = useCallback(
    (value: string) => {
      if (!artifact) return;
      setDraftById((prev) => ({ ...prev, [artifact.id]: value }));
    },
    [artifact],
  );

  const handleCodeBlur = useCallback(() => {
    if (!artifact || !isCodeDirty) return;
    void commitArtifactEdit(artifact, codeDraft);
  }, [artifact, codeDraft, commitArtifactEdit, isCodeDirty]);

  const handleMermaidBlur = useCallback(
    (value: string) => {
      if (!artifact || artifact.type !== "mermaid") return;
      void commitArtifactEdit(artifact, value);
    },
    [artifact, commitArtifactEdit],
  );

  // Handle drag start
  const handleDragStart = useCallback(
    (e: React.MouseEvent) => {
      if (isFullscreen) return;
      e.preventDefault();
      setIsDragging(true);
      setDragStart({ x: e.clientX, y: e.clientY });
      setInitialPos({ ...position });
    },
    [position, isFullscreen],
  );

  // Handle resize start
  const handleResizeStart = useCallback(
    (e: React.MouseEvent, direction: string) => {
      if (isFullscreen) return;
      e.preventDefault();
      e.stopPropagation();
      setIsResizing(direction);
      setDragStart({ x: e.clientX, y: e.clientY });
      setInitialPos({ ...position });
      setInitialSize({ ...size });
    },
    [position, size, isFullscreen],
  );

  // Handle mouse move for drag and resize
  useEffect(() => {
    const handleMouseMove = (e: MouseEvent) => {
      if (isDragging) {
        const dx = e.clientX - dragStart.x;
        const dy = e.clientY - dragStart.y;
        setPosition({
          x: Math.max(
            0,
            Math.min(window.innerWidth - size.width, initialPos.x + dx),
          ),
          y: Math.max(
            0,
            Math.min(window.innerHeight - size.height, initialPos.y + dy),
          ),
        });
      } else if (isResizing) {
        const dx = e.clientX - dragStart.x;
        const dy = e.clientY - dragStart.y;

        let newWidth = initialSize.width;
        let newHeight = initialSize.height;
        let newX = initialPos.x;
        let newY = initialPos.y;

        // Handle resize directions
        if (isResizing.includes("e")) {
          newWidth = Math.max(MIN_WIDTH, initialSize.width + dx);
        }
        if (isResizing.includes("w")) {
          const proposedWidth = initialSize.width - dx;
          if (proposedWidth >= MIN_WIDTH) {
            newWidth = proposedWidth;
            newX = initialPos.x + dx;
          }
        }
        if (isResizing.includes("s")) {
          newHeight = Math.max(MIN_HEIGHT, initialSize.height + dy);
        }
        if (isResizing.includes("n")) {
          const proposedHeight = initialSize.height - dy;
          if (proposedHeight >= MIN_HEIGHT) {
            newHeight = proposedHeight;
            newY = initialPos.y + dy;
          }
        }

        setSize({ width: newWidth, height: newHeight });
        setPosition({ x: newX, y: newY });
      }
    };

    const handleMouseUp = () => {
      setIsDragging(false);
      setIsResizing(null);
    };

    if (isDragging || isResizing) {
      document.addEventListener("mousemove", handleMouseMove);
      document.addEventListener("mouseup", handleMouseUp);
      return () => {
        document.removeEventListener("mousemove", handleMouseMove);
        document.removeEventListener("mouseup", handleMouseUp);
      };
    }
  }, [isDragging, isResizing, dragStart, initialPos, initialSize, size]);

  // Close on escape key
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape" && isVisible) {
        handleClose();
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [isVisible, handleClose]);

  // Render content based on artifact type
  const renderContent = () => {
    if (!artifact) return null;
    if (artifact.type === "mermaid") {
      if (viewMode === "editor") {
        return (
          <MermaidEditor
            artifact={artifact}
            onContentBlur={handleMermaidBlur}
          />
        );
      }
      if (viewMode === "code") {
        return (
          <CodeRenderer
            content={artifact.content}
            language={artifact.language || artifact.type}
          />
        );
      }
      return <MermaidRenderer content={artifact.content} id={artifact.id} />;
    }

    if (artifact.type === "html") {
      if (viewMode === "editor") {
        return (
          <CodeEditor
            value={codeDraft}
            language={artifact.type}
            onChange={handleCodeChange}
            onBlur={handleCodeBlur}
            placeholder="Edit HTML markup..."
          />
        );
      }
      return (
        <iframe
          srcDoc={artifact.content}
          className="w-full h-full min-h-[400px] bg-white rounded-lg"
          sandbox="allow-scripts"
          title={artifact.title}
        />
      );
    }

    if (artifact.type === "react" || artifact.type === "code") {
      if (viewMode === "editor") {
        return (
          <CodeEditor
            value={codeDraft}
            language={artifact.language || artifact.type}
            onChange={handleCodeChange}
            onBlur={handleCodeBlur}
            placeholder="Edit code..."
          />
        );
      }
      return (
        <CodeRenderer
          content={artifact.content}
          language={artifact.language || artifact.type}
        />
      );
    }

    switch (artifact.type) {
      case "image": {
        const imageSrc = artifact.imageData
          ? `data:${artifact.mimeType || "image/png"};base64,${artifact.imageData}`
          : artifact.imageUrl || artifact.content || null;
        const sourceUrl = toExternalHttpUrl(
          artifact.pageUrl || artifact.imageUrl || artifact.content,
        );
        const linkedUrl = toExternalHttpUrl(artifact.content);
        const hasFailed = Boolean(failedImageArtifacts[artifact.id]);

        if (!imageSrc || hasFailed) {
          return (
            <div className="flex flex-col items-center justify-center h-full gap-4 text-muted-foreground">
              <svg
                className="w-16 h-16 opacity-50"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={1.5}
                  d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"
                />
              </svg>
              <span className="text-sm">
                {hasFailed ? "Image failed to load" : "Image unavailable"}
              </span>
              <div className="flex items-center gap-3 text-xs">
                {sourceUrl && (
                  <a
                    href={sourceUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-primary hover:text-primary/80 underline underline-offset-2"
                  >
                    Open source
                  </a>
                )}
                {linkedUrl && linkedUrl !== sourceUrl && (
                  <a
                    href={linkedUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-muted-foreground hover:text-foreground underline underline-offset-2"
                  >
                    Open linked URL
                  </a>
                )}
              </div>
              {sourceUrl && (
                <LinkPreview url={sourceUrl}>
                  <a
                    href={sourceUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-xs text-muted-foreground hover:text-foreground underline underline-offset-2"
                  >
                    Preview source
                  </a>
                </LinkPreview>
              )}
            </div>
          );
        }
        return (
          <div className="flex flex-col items-center justify-center h-full gap-4">
            <img
              src={imageSrc}
              alt={artifact.altText || artifact.title}
              className="max-w-full max-h-[calc(100%-4rem)] object-contain rounded-lg shadow-lg"
              onError={() => {
                setFailedImageArtifacts((prev) => ({
                  ...prev,
                  [artifact.id]: true,
                }));
              }}
            />
            {(artifact.aspectRatio || artifact.resolution) && (
              <div className="flex items-center gap-3 text-sm text-muted-foreground">
                {artifact.aspectRatio && (
                  <span className="px-2 py-0.5 bg-secondary rounded">
                    {artifact.aspectRatio}
                  </span>
                )}
                {artifact.resolution && (
                  <span className="px-2 py-0.5 bg-secondary rounded">
                    {artifact.resolution}
                  </span>
                )}
              </div>
            )}
          </div>
        );
      }

      case "kb-article":
      case "article":
        return <ArticleEditor key={artifact.id} artifact={artifact} />;

      default:
        return (
          <CodeRenderer
            content={artifact.content}
            language={artifact.language || artifact.type}
          />
        );
    }
  };

  return (
    <AnimatePresence>
      {isVisible && artifact && (
        <>
          {/* Backdrop - click to close */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2 }}
            className={cn(
              "fixed inset-0 z-[100]",
              isMobile
                ? "bg-black/60 backdrop-blur-sm"
                : "bg-background/80 backdrop-blur-sm",
            )}
            onClick={handleClose}
          />

          {/* Panel - Mobile or Desktop */}
          <motion.div
            ref={panelRef}
            initial={isMobile ? { y: "100%" } : { opacity: 0, scale: 0.95 }}
            animate={isMobile ? { y: 0 } : { opacity: 1, scale: 1 }}
            exit={isMobile ? { y: "100%" } : { opacity: 0, scale: 0.95 }}
            transition={{ duration: 0.25, ease: [0.4, 0, 0.2, 1] }}
            className={cn(
              "fixed z-[101] bg-card border border-border shadow-2xl overflow-hidden flex flex-col",
              isMobile ? "inset-x-0 bottom-0 rounded-t-2xl" : "rounded-xl",
              (isDragging || isResizing || isMobileDragging) && "select-none",
            )}
            style={
              isMobile
                ? { height: `${mobileHeight}vh` }
                : isFullscreen
                  ? {
                      top: 16,
                      left: 16,
                      right: 16,
                      bottom: 16,
                      width: "auto",
                      height: "auto",
                    }
                  : {
                      top: position.y,
                      left: position.x,
                      width: size.width,
                      height: size.height,
                    }
            }
            onClick={(e) => e.stopPropagation()}
          >
            {/* Mobile drag handle */}
            {isMobile && (
              <div
                className="flex-shrink-0 flex items-center justify-center py-2 cursor-grab active:cursor-grabbing bg-secondary/30"
                onPointerDown={handleMobileDragStart}
                onPointerMove={handleMobileDragMove}
                onPointerUp={handleMobileDragEnd}
                onPointerCancel={handleMobileDragEnd}
              >
                <div className="w-10 h-1 rounded-full bg-muted-foreground/40" />
              </div>
            )}

            {/* Resize handles (only when not fullscreen and not mobile) */}
            {!isFullscreen && !isMobile && (
              <>
                {/* Edge handles */}
                <ResizeHandle
                  direction="n"
                  className="top-0 left-4 right-4 h-2 -mt-1"
                  isActive={isResizing === "n"}
                  onResizeStart={handleResizeStart}
                />
                <ResizeHandle
                  direction="s"
                  className="bottom-0 left-4 right-4 h-2 -mb-1"
                  isActive={isResizing === "s"}
                  onResizeStart={handleResizeStart}
                />
                <ResizeHandle
                  direction="e"
                  className="right-0 top-4 bottom-4 w-2 -mr-1"
                  isActive={isResizing === "e"}
                  onResizeStart={handleResizeStart}
                />
                <ResizeHandle
                  direction="w"
                  className="left-0 top-4 bottom-4 w-2 -ml-1"
                  isActive={isResizing === "w"}
                  onResizeStart={handleResizeStart}
                />
                {/* Corner handles */}
                <ResizeHandle
                  direction="nw"
                  className="top-0 left-0 w-4 h-4 -mt-1 -ml-1"
                  isActive={isResizing === "nw"}
                  onResizeStart={handleResizeStart}
                />
                <ResizeHandle
                  direction="ne"
                  className="top-0 right-0 w-4 h-4 -mt-1 -mr-1"
                  isActive={isResizing === "ne"}
                  onResizeStart={handleResizeStart}
                />
                <ResizeHandle
                  direction="sw"
                  className="bottom-0 left-0 w-4 h-4 -mb-1 -ml-1"
                  isActive={isResizing === "sw"}
                  onResizeStart={handleResizeStart}
                />
                <ResizeHandle
                  direction="se"
                  className="bottom-0 right-0 w-4 h-4 -mb-1 -mr-1"
                  isActive={isResizing === "se"}
                  onResizeStart={handleResizeStart}
                />
              </>
            )}

            {/* Header - draggable on desktop */}
            <div
              className={cn(
                "flex items-center justify-between px-4 py-3 border-b border-border bg-secondary/30",
                !isFullscreen && !isMobile && "cursor-move",
              )}
              onMouseDown={!isMobile ? handleDragStart : undefined}
            >
              <div className="flex items-center gap-2 min-w-0">
                {/* Artifact navigation */}
                {hasMultipleArtifacts && (
                  <div className="flex items-center gap-0.5 mr-1">
                    <button
                      onClick={handlePrevArtifact}
                      disabled={currentIndex <= 0}
                      className={cn(
                        "p-1 rounded hover:bg-secondary transition-colors",
                        currentIndex <= 0
                          ? "text-muted-foreground/30 cursor-not-allowed"
                          : "text-muted-foreground hover:text-foreground",
                      )}
                      title="Previous artifact"
                    >
                      <ChevronLeft className="h-4 w-4" />
                    </button>
                    <span className="text-xs text-muted-foreground tabular-nums">
                      {currentIndex + 1}/{orderedIds.length}
                    </span>
                    <button
                      onClick={handleNextArtifact}
                      disabled={currentIndex >= orderedIds.length - 1}
                      className={cn(
                        "p-1 rounded hover:bg-secondary transition-colors",
                        currentIndex >= orderedIds.length - 1
                          ? "text-muted-foreground/30 cursor-not-allowed"
                          : "text-muted-foreground hover:text-foreground",
                      )}
                      title="Next artifact"
                    >
                      <ChevronRight className="h-4 w-4" />
                    </button>
                  </div>
                )}

                {!isFullscreen && !isMobile && (
                  <GripVertical className="h-4 w-4 text-muted-foreground/50 flex-shrink-0" />
                )}
                <h2 className="font-semibold text-foreground truncate max-w-[200px] sm:max-w-[300px]">
                  {artifact.title}
                </h2>
                <span className="px-2 py-0.5 rounded-full bg-primary/20 text-primary text-xs font-medium flex-shrink-0">
                  {artifact.type}
                </span>
              </div>

              <div
                className="flex items-center gap-1"
                onMouseDown={(e) => e.stopPropagation()}
              >
                {isMermaid && (
                  <div className="flex items-center bg-secondary rounded-lg p-0.5 mr-2">
                    <button
                      onClick={() => setViewMode("preview")}
                      className={cn(
                        "px-2 py-1 rounded text-xs font-medium transition-colors",
                        viewMode === "preview"
                          ? "bg-primary text-primary-foreground"
                          : "text-muted-foreground hover:text-foreground",
                      )}
                      title="Preview"
                    >
                      <Eye className="h-3.5 w-3.5" />
                    </button>
                    <button
                      onClick={() => setViewMode("editor")}
                      className={cn(
                        "px-2 py-1 rounded text-xs font-medium transition-colors",
                        viewMode === "editor"
                          ? "bg-primary text-primary-foreground"
                          : "text-muted-foreground hover:text-foreground",
                      )}
                      title="Edit"
                    >
                      <Edit3 className="h-3.5 w-3.5" />
                    </button>
                    <button
                      onClick={() => setViewMode("code")}
                      className={cn(
                        "px-2 py-1 rounded text-xs font-medium transition-colors",
                        viewMode === "code"
                          ? "bg-primary text-primary-foreground"
                          : "text-muted-foreground hover:text-foreground",
                      )}
                      title="Code"
                    >
                      <Code className="h-3.5 w-3.5" />
                    </button>
                  </div>
                )}

                {isHtml && (
                  <div className="flex items-center bg-secondary rounded-lg p-0.5 mr-2">
                    <button
                      onClick={() => setViewMode("preview")}
                      className={cn(
                        "px-2 py-1 rounded text-xs font-medium transition-colors",
                        viewMode === "preview"
                          ? "bg-primary text-primary-foreground"
                          : "text-muted-foreground hover:text-foreground",
                      )}
                      title="Preview"
                    >
                      <Eye className="h-3.5 w-3.5" />
                    </button>
                    <button
                      onClick={() => setViewMode("editor")}
                      className={cn(
                        "px-2 py-1 rounded text-xs font-medium transition-colors",
                        viewMode === "editor"
                          ? "bg-primary text-primary-foreground"
                          : "text-muted-foreground hover:text-foreground",
                      )}
                      title="Edit"
                    >
                      <Edit3 className="h-3.5 w-3.5" />
                    </button>
                  </div>
                )}

                {isCodeArtifact && (
                  <div className="flex items-center bg-secondary rounded-lg p-0.5 mr-2">
                    <button
                      onClick={() => setViewMode("code")}
                      className={cn(
                        "px-2 py-1 rounded text-xs font-medium transition-colors",
                        viewMode === "code"
                          ? "bg-primary text-primary-foreground"
                          : "text-muted-foreground hover:text-foreground",
                      )}
                      title="Code"
                    >
                      <Code className="h-3.5 w-3.5" />
                    </button>
                    <button
                      onClick={() => setViewMode("editor")}
                      className={cn(
                        "px-2 py-1 rounded text-xs font-medium transition-colors",
                        viewMode === "editor"
                          ? "bg-primary text-primary-foreground"
                          : "text-muted-foreground hover:text-foreground",
                      )}
                      title="Edit"
                    >
                      <Edit3 className="h-3.5 w-3.5" />
                    </button>
                  </div>
                )}

                <button
                  onClick={handleCopy}
                  className="p-2 rounded-lg hover:bg-secondary transition-colors text-muted-foreground hover:text-foreground"
                  title="Copy code"
                >
                  {copied ? (
                    <Check className="h-4 w-4 text-green-500" />
                  ) : (
                    <Copy className="h-4 w-4" />
                  )}
                </button>

                <button
                  onClick={handleDownload}
                  className="p-2 rounded-lg hover:bg-secondary transition-colors text-muted-foreground hover:text-foreground"
                  title="Download"
                >
                  <Download className="h-4 w-4" />
                </button>

                {!isMobile && (
                  <button
                    onClick={() => setIsFullscreen(!isFullscreen)}
                    className="p-2 rounded-lg hover:bg-secondary transition-colors text-muted-foreground hover:text-foreground"
                    title={isFullscreen ? "Exit fullscreen" : "Fullscreen"}
                  >
                    {isFullscreen ? (
                      <Minimize2 className="h-4 w-4" />
                    ) : (
                      <Maximize2 className="h-4 w-4" />
                    )}
                  </button>
                )}

                <button
                  onClick={handleDelete}
                  className="p-2 rounded-lg hover:bg-red-500/20 transition-colors text-muted-foreground hover:text-red-400"
                  title="Delete artifact"
                >
                  <Trash2 className="h-4 w-4" />
                </button>

                <button
                  onClick={handleClose}
                  className="p-2 rounded-lg hover:bg-secondary transition-colors text-muted-foreground hover:text-foreground ml-1"
                  title="Close (Esc)"
                >
                  <X className="h-4 w-4" />
                </button>
              </div>
            </div>

            {/* Content */}
            <div
              className={cn(
                "flex-1 overflow-auto bg-background/50",
                viewMode !== "editor" && "p-4",
              )}
            >
              {renderContent()}
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
});

export default ArtifactPanel;
