-- Create sparrow_feedback table for global feedback submissions with RLS and indexes

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS public.sparrow_feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  kind TEXT NOT NULL DEFAULT 'feedback',
  feedback_text TEXT NOT NULL,
  selected_text TEXT NULL,
  attachments JSONB NOT NULL DEFAULT '[]'::jsonb,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  embedding VECTOR(3072),
  status TEXT NOT NULL DEFAULT 'received',
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

-- Ensure RLS and grants are configured idempotently
ALTER TABLE IF EXISTS public.sparrow_feedback ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT ON TABLE public.sparrow_feedback TO authenticated;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'sparrow_feedback'
      AND policyname = 'sparrow_feedback_select_authenticated'
  ) THEN
    EXECUTE 'CREATE POLICY sparrow_feedback_select_authenticated ON public.sparrow_feedback
             FOR SELECT TO authenticated
             USING (auth.uid() = user_id)';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'sparrow_feedback'
      AND policyname = 'sparrow_feedback_insert_authenticated'
  ) THEN
    EXECUTE 'CREATE POLICY sparrow_feedback_insert_authenticated ON public.sparrow_feedback
             FOR INSERT TO authenticated
             WITH CHECK (auth.uid() = user_id)';
  END IF;
END $$;

-- Indexes for query performance
CREATE INDEX IF NOT EXISTS idx_sparrow_feedback_created_at_desc
  ON public.sparrow_feedback (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_sparrow_feedback_metadata_gin
  ON public.sparrow_feedback
  USING GIN (metadata);
