-- Create sparrow_corrections table for global correction submissions with RLS and indexes

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS public.sparrow_corrections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  kind TEXT NOT NULL DEFAULT 'correction',
  incorrect_text TEXT NOT NULL,
  corrected_text TEXT NOT NULL,
  explanation TEXT NULL,
  attachments JSONB NOT NULL DEFAULT '[]'::jsonb,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  embedding VECTOR(3072),
  status TEXT NOT NULL DEFAULT 'received',
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

ALTER TABLE IF EXISTS public.sparrow_corrections ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT ON TABLE public.sparrow_corrections TO authenticated;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'sparrow_corrections'
      AND policyname = 'sparrow_corrections_select_authenticated'
  ) THEN
    EXECUTE 'CREATE POLICY sparrow_corrections_select_authenticated ON public.sparrow_corrections
             FOR SELECT TO authenticated
             USING (auth.uid() = user_id)';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'sparrow_corrections'
      AND policyname = 'sparrow_corrections_insert_authenticated'
  ) THEN
    EXECUTE 'CREATE POLICY sparrow_corrections_insert_authenticated ON public.sparrow_corrections
             FOR INSERT TO authenticated
             WITH CHECK (auth.uid() = user_id)';
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_sparrow_corrections_created_at_desc
  ON public.sparrow_corrections (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_sparrow_corrections_metadata_gin
  ON public.sparrow_corrections
  USING GIN (metadata);
