-- Zendesk integration tables: pending tickets queue, monthly usage, and feature flags

-- Feature flags (server-managed; no policies for authenticated users)
CREATE TABLE IF NOT EXISTS public.feature_flags (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

ALTER TABLE IF EXISTS public.feature_flags ENABLE ROW LEVEL SECURITY;
-- No RLS policies for anonymous/authenticated; service role will bypass RLS.
REVOKE ALL ON public.feature_flags FROM anon, authenticated;

-- Pending tickets captured from Zendesk webhooks (no backfill semantics)
CREATE TABLE IF NOT EXISTS public.zendesk_pending_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT NOT NULL,
  brand_id TEXT NULL,
  subject TEXT NULL,
  description TEXT NULL,
  requester_hashed TEXT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'pending',        -- pending | processed | failed | dropped
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  processed_at TIMESTAMPTZ NULL,
  CONSTRAINT zendesk_pending_tickets_ticket_unique UNIQUE (ticket_id)
);

ALTER TABLE IF EXISTS public.zendesk_pending_tickets ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.zendesk_pending_tickets FROM anon, authenticated;

CREATE INDEX IF NOT EXISTS idx_zpt_created_at_desc
  ON public.zendesk_pending_tickets (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_zpt_status_created
  ON public.zendesk_pending_tickets (status, created_at DESC);

-- Monthly API usage tracking (to enforce budget like 350 calls/month)
CREATE TABLE IF NOT EXISTS public.zendesk_usage (
  month_key TEXT PRIMARY KEY,        -- format YYYY-MM in UTC
  calls_used INT NOT NULL DEFAULT 0,
  budget INT NOT NULL DEFAULT 350,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

ALTER TABLE IF EXISTS public.zendesk_usage ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.zendesk_usage FROM anon, authenticated;

-- Helpful default row for current month (idempotent upsert)
DO $$
DECLARE
  mk TEXT := to_char(timezone('utc', now()), 'YYYY-MM');
BEGIN
  INSERT INTO public.zendesk_usage (month_key, calls_used, budget)
  VALUES (mk, 0, 350)
  ON CONFLICT (month_key) DO NOTHING;
END $$;
